====================
django-server-config
====================

Server config for your project.

It will generate config for lighttpd, logrotate and monit.

Now you don`t need to copy or make links to media in 3-party applications.

Installation:
=============

In settings.py:
---------------

1. Put ``config`` to your ``INSTALLED_APPS``.

2. Set sites to be served by your project::

    CONFIG_SITES = ['www.project-name.com', ]

3. Set sites to be redirected from::

    CONFIG_REDIRECTS = ['project-name.com', ]

4. Set path to media for unusual 3-parry application (you can just skip this setting)::

    CONFIG_APP_MEDIA = {
        'application-name': [
            ('media-root', 'media-url', ),
        ]
    }

In urls.py:
-----------

5. Add config to urls.py for serve static files in debug mode. Add it BEFORE ``django.views.static.serve``::

    if settings.DEBUG:
        urlpatterns += patterns('', (r'^', include('config.urls')))


In buildout.cfg:
----------------

6. If you are using zc.buildout, you can add to your parts ``make-config`` to make config files automaticaly::

    [make-config]
    recipe = iw.recipe.cmd
    on_install = true
    on_update = true
    cmds = sudo rm -f bin/init.d bin/lighttpd bin/logrotate bin/monit
           bin/django make_config init.d > bin/init.d
           bin/django make_config lighttpd > bin/lighttpd
           bin/django make_config logrotate > bin/logrotate
           bin/django make_config monit > bin/monit
           sudo chown root:root bin/init.d bin/lighttpd bin/logrotate bin/monit
           sudo chmod ug=rwx,o=rx bin/init.d
           sudo chmod ug=rw,o=r bin/lighttpd bin/logrotate bin/monit
           echo Configs were saved to "bin/"

Usage:
======

On server you can create symlinks to config files, generated by django-server-config.

init.d script:
--------------

1. Create link to run your django project using ``invoke-rc.d``::

    sudo ln -s <project-dir>/bin/init.d /etc/init.d/<project-name>

lighttpd config:
----------------

2. Create link to your lighttpd configuration::

    sudo ln -s <project-dir>/bin/lighttpd /etc/lighttpd/conf-available/11-<project-name>.conf

3. Create link for enabled lighttpd configuration::

    sudo ln -s /etc/lighttpd/conf-available/11-<project-name>.conf /etc/lighttpd/conf-enabled/11-<project-name>.conf

4. Don`t forget to reload lighttpd configuration::

    sudo invoke-rc.d lighttpd reload

logrotate config:
-----------------

5. Create link to logrotate configuration::

    sudo ln -s <project-dir>/bin/logrotate /etc/logrotate.d/<project-name>

monit config:
-------------

6. Create link to your monit configuration::

    sudo ln -s <project-dir>/bin/monit /etc/monit/services-available/<project-name>

7. Create link for enabled monit configuration::

    sudo ln -s /etc/monit/services-available/<project-name> /etc/monit/services-enabled/<project-name>

8. Don`t forget to reload monit configuration::

    sudo monit reload

